plugins {
    id 'java'
}

group = 'cn.xinyue-neko.plugin'
version = '1.0.1'

repositories {
    mavenCentral()
    maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    maven { url = 'https://jitpack.io' }
    maven { url = 'https://repo.papermc.io/repository/maven-public'}
    maven { url = 'https://oss.sonatype.org/content/repositories/snapshots' }
    maven { url = 'https://oss.sonatype.org/content/repositories/central' }
}

dependencies {
    compileOnly('org.spigotmc:spigot-api:1.13.2-R0.1-SNAPSHOT') {
        transitive = false
    }
    compileOnly('com.destroystokyo.paper:paper-api:1.13.2-R0.1-SNAPSHOT') {
        transitive = false
    }
    compileOnly('com.github.MilkBowl:VaultAPI:1.7') {
        transitive = false
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    archiveBaseName = 'SimpleSign'
}